### PR TITLE
make rebar3 build examples in test prof

### PR DESCRIPTION
**Pull request by uwiger**
run rebar3 eunit in travis

By adding a `test` profile that at least compiles the `examples` code, CI is improved a bit more.

### CODE REVIEW

**Comment by uwiger** [comment]
And what do you know – it fails on 17.5!

**Comment by fenollp** [comment]
How about we drop 17.5?

**Comment by uwiger** [comment]
That's fine by me. :)

**Comment by fenollp** [comment]
Good!

**Comment by uwiger** [comment]
Ok, back to our regularly scheduled program ...

**Pull request merged**
